### PR TITLE
- Verify if there is enough free space on disk (ex: 25GB) to install a node + lower case user input

### PR DESCRIPTION
**Pull request by dwildcash**
My first little contribution.

- Check if there is enough free space in the LISK_LOCATION to install a node. (exemple 25GB could be adjusted)
- Make sure user input are all in lower case to avoid comparaison issue.  (I was always entering Test instead of test)

- dwildcash

### CODE REVIEW

**Comment by dwildcash** [comment]
I fixed Jenkins validation warning

**Comment by Nazgolze** [comment]
Hello @dwildcash.

Thank you for your contribution 🙂
`lisk-scripts` is getting phased out as this functionality will eventually be handled elsewhere

As a result, we're not taking pull requests for this unless it's critical

I do like the idea of a disk space check though. You might want to keep your eyes peeled for it in https://github.com/LiskHQ/lisk-core/tree/development/src/commands (I think this is where it will be) for when the install functionality gets implemented

**Comment by Nazgolze** [comment]
Closes #201

**Comment by nerdvibe** [comment]
> `lisk-scripts` is getting phased out as this functionality will eventually be handled elsewhere

@Nazgolze 😢

**Pull request closed without merging**
