### PR TITLE
Update path and filename of config migrate script

### LINKED ISSUE #66: Update the path and filename for config migration script
As we moved the configuration migration script to core with https://github.com/LiskHQ/lisk/issues/2046 so we have to update the new path name for the file in `installLisk.sh` file. 

The new file path for that script is `scripts/update_config.js` You ca see more details on https://github.com/LiskHQ/lisk/pull/2048

Also the parameters are different, instead of optional params now we pass command arguments. 

```
node update_config.js <old_config_path> <new_config_path>
```

### PR DESCRIPTION
**Pull request by Nazgolze**
Update path and filename of config migrate script - Closes #66 

Depends on https://github.com/LiskHQ/lisk/issues/2046

### CODE REVIEW

**Comment by Nazgolze** [comment]
I was thinking the same thing when I pushed it. It definitely isn't

**Comment by fchavant** [comment]
Which is unfortunate. Do we really need to rename that file?

**Comment by Nazgolze** [comment]
It might be good to see how https://github.com/LiskHQ/lisk/issues/2046 ends up
I pushed something up that should work, but it's less than ideal. I'll suspend this PR for now

**Comment by Nazgolze** [comment]
https://github.com/LiskHQ/lisk/pull/2048 has been merged

**Comment by nazarhussain** [comment]
@Nazgolze Must see this comment https://github.com/LiskHQ/lisk-scripts/issues/66#issuecomment-395018539

**Comment by Nazgolze** [comment]
Closed by #84

**Pull request closed without merging**
